### ISSUE TITLE
Clone with Submodule  is not possible

### ISSUE THREAD

**Issue by mgiaco** [uCAN-LIN/LinUSBConverter#1]
I think there is something wrong. Have you tried to do a fresh clone with this master?
```
git clone https://github.com/uCAN-LIN/LinUSBConverter.git --recurse-submodules
```
If you try that you will see that the submodule  setting is not correct. So could it be that your have not updated the .gitmodules?

I try to use that as an example.

cheers 
mathias

**Comment by Lukasz-Juranek** [comment]
Test three are issues with submodules, ill Fox this shortly

wt., 6 sie 2019, 15:18 użytkownik Mathias Giacomuzzi <
notifications@github.com> napisał:

**Comment by iDoka** [comment]
@mgiaco I dont know the purpose of folder `embedded_LIN_GS` but for submodule `open-LIN-c` I solved issue with following way:
0. `git clone https://github.com/uCAN-LIN/LinUSBConverter && cd LinUSBConverter`
1. edit `.gitmodules` as follow:
```
[submodule "embedded/Src/open-LIN-c"]
	path = embedded/Src/open-LIN-c
	url = https://github.com/open-LIN/open-LIN-c.git

```
2. do:
```
git submodule init
git submodule update --recursive
```

**Comment by Lukasz-Juranek** [comment]
I've updated .gitmodules file
